---
abstract: 'Fix the encoding for Perl value store (input) and general output (output) to a console or the web.'
author:
  - 'BURNERSK <burnersk@cpan.org>'
build_requires:
  English: '0'
  Test::More: '0'
  Test::NoWarnings: '0'
  Test::Warn: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.142690'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Encoding-HandleUtf8
no_index:
  directory:
    - example
    - t
provides:
  Encoding::HandleUtf8:
    file: lib/Encoding/HandleUtf8.pm
requires:
  Carp: '0'
  Clone: '0'
  Encoding::FixLatin: '0'
  Exporter: '0'
  List::Util: '0'
  base: '0'
  perl: '5.010'
resources:
  bugtracker: https://github.com/burnersk/Encoding-HandleUtf8/issues
  homepage: https://github.com/burnersk/Encoding-HandleUtf8
  repository: https://github.com/burnersk/Encoding-HandleUtf8.git
version: '0.004'
x_contributors:
  - 'BURNERSK <burnersk@cpan.org>'
